batch_log_interval: 100
batch_size: 64
batch_size_test: 2000
epochs: 2
load_weights_file: ''
loss_func: CrossEntropyLoss
lr: 0.001
n_filters: 32
n_unit_hidden: 128
optimizer_name: Adam
seed: 1234
use_cuda: false
